server:
  port: 8090

spring:
  application:
    name: tb-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #═Нит├Ч├ч

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
